# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'stormsim_4_10xBBZfr.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QComboBox, QDateTimeEdit,
    QDoubleSpinBox, QFrame, QGridLayout, QGroupBox,
    QHBoxLayout, QHeaderView, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QPlainTextEdit,
    QPushButton, QSizePolicy, QSpacerItem, QStatusBar,
    QTabWidget, QTableView, QTableWidget, QTableWidgetItem,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1389, 882)
        MainWindow.setMinimumSize(QSize(1389, 882))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.header = QFrame(self.centralwidget)
        self.header.setObjectName(u"header")
        self.header.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QSize(1371, 71))
        self.header.setMaximumSize(QSize(16777215, 71))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(20)
        self.header.setFont(font)
        self.header.setFrameShape(QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.header)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_10_stormsim_logo = QLabel(self.header)
        self.label_10_stormsim_logo.setObjectName(u"label_10_stormsim_logo")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_10_stormsim_logo.sizePolicy().hasHeightForWidth())
        self.label_10_stormsim_logo.setSizePolicy(sizePolicy1)
        self.label_10_stormsim_logo.setMinimumSize(QSize(213, 51))
        self.label_10_stormsim_logo.setMaximumSize(QSize(213, 51))
        self.label_10_stormsim_logo.setTextFormat(Qt.TextFormat.RichText)
        self.label_10_stormsim_logo.setPixmap(QPixmap(u"thumbnail_SSLogo (transparent, Qt designer fit).png"))
        self.label_10_stormsim_logo.setScaledContents(True)

        self.horizontalLayout.addWidget(self.label_10_stormsim_logo)

        self.label_2 = QLabel(self.header)
        self.label_2.setObjectName(u"label_2")
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QSize(801, 51))
        self.label_2.setMaximumSize(QSize(16777215, 51))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(31)
        font1.setBold(True)
        font1.setItalic(False)
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.label_2)

        self.label_2_chl_logo = QLabel(self.header)
        self.label_2_chl_logo.setObjectName(u"label_2_chl_logo")
        self.label_2_chl_logo.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.label_2_chl_logo.sizePolicy().hasHeightForWidth())
        self.label_2_chl_logo.setSizePolicy(sizePolicy1)
        self.label_2_chl_logo.setMinimumSize(QSize(320, 51))
        self.label_2_chl_logo.setMaximumSize(QSize(320, 51))
        self.label_2_chl_logo.setFrameShape(QFrame.Shape.NoFrame)
        self.label_2_chl_logo.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_2_chl_logo.setTextFormat(Qt.TextFormat.RichText)
        self.label_2_chl_logo.setPixmap(QPixmap(u"CHL_banner3 (Qt designer fit).png"))
        self.label_2_chl_logo.setScaledContents(True)

        self.horizontalLayout.addWidget(self.label_2_chl_logo)


        self.gridLayout.addWidget(self.header, 0, 0, 1, 3)

        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy2)
        self.tabWidget.setMinimumSize(QSize(671, 761))
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        self.tabWidget.setFont(font2)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.gridLayout_2 = QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy1.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy1)
        self.groupBox.setMinimumSize(QSize(647, 180))
        font3 = QFont()
        font3.setPointSize(19)
        font3.setBold(True)
        self.groupBox.setFont(font3)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QRect(20, 38, 611, 131))
        self.label_4.setMinimumSize(QSize(611, 111))
        font4 = QFont()
        font4.setFamilies([u"Segoe UI"])
        font4.setPointSize(12)
        font4.setBold(False)
        font4.setUnderline(False)
        self.label_4.setFont(font4)
        self.label_4.setTextFormat(Qt.TextFormat.RichText)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.label_4.setWordWrap(True)

        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy2)
        self.groupBox_3.setMinimumSize(QSize(647, 371))
        self.groupBox_3.setFont(font3)
        self.verticalLayout = QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.frame = QFrame(self.groupBox_3)
        self.frame.setObjectName(u"frame")
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setMinimumSize(QSize(630, 31))
        self.frame.setMaximumSize(QSize(16777215, 16777215))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.lineEdit = QLineEdit(self.frame)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(9, 2, 351, 22))
        self.lineEdit.setMinimumSize(QSize(351, 22))
        self.lineEdit.setMaximumSize(QSize(16777215, 22))
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(False)
        self.lineEdit.setFont(font5)
        self.pushButton_3 = QPushButton(self.frame)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QRect(460, 0, 81, 26))
        sizePolicy1.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy1)
        self.pushButton_3.setMinimumSize(QSize(81, 26))
        self.pushButton_3.setMaximumSize(QSize(81, 26))
        font6 = QFont()
        font6.setPointSize(11)
        font6.setBold(True)
        self.pushButton_3.setFont(font6)
        self.pushButton_3.setStyleSheet(u"QPushButton { background-color: red;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: 1px solid black;\n"
"border-style: outset;\n"
"border-radius: 6px;}\n"
"QPushButton:hover { border: 1px solid rgb(0, 120, 212);\n"
"background-color: rgb(245, 0, 100) }\n"
"QPushButton:pressed { background-color: rgb(224, 0, 0);\n"
"border-style: inset }")
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QRect(370, 0, 81, 26))
        sizePolicy1.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy1)
        self.pushButton_2.setMinimumSize(QSize(81, 26))
        self.pushButton_2.setMaximumSize(QSize(81, 26))
        self.pushButton_2.setFont(font6)
        self.pushButton_1 = QPushButton(self.frame)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setGeometry(QRect(550, 0, 71, 26))
        sizePolicy1.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy1)
        self.pushButton_1.setMinimumSize(QSize(71, 26))
        font7 = QFont()
        font7.setPointSize(11)
        font7.setBold(False)
        self.pushButton_1.setFont(font7)

        self.verticalLayout.addWidget(self.frame)

        self.tableWidget = QTableWidget(self.groupBox_3)
        if (self.tableWidget.columnCount() < 2):
            self.tableWidget.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        if (self.tableWidget.rowCount() < 3):
            self.tableWidget.setRowCount(3)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setCheckState(Qt.Checked);
        __qtablewidgetitem5.setFlags(Qt.ItemIsDragEnabled|Qt.ItemIsDropEnabled|Qt.ItemIsUserCheckable|Qt.ItemIsEnabled);
        self.tableWidget.setItem(0, 0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setCheckState(Qt.Checked);
        self.tableWidget.setItem(0, 1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setCheckState(Qt.Checked);
        self.tableWidget.setItem(1, 0, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setCheckState(Qt.Checked);
        self.tableWidget.setItem(1, 1, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setCheckState(Qt.Checked);
        self.tableWidget.setItem(2, 0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        __qtablewidgetitem10.setCheckState(Qt.Checked);
        self.tableWidget.setItem(2, 1, __qtablewidgetitem10)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setEnabled(True)
        self.tableWidget.setMinimumSize(QSize(630, 291))
        font8 = QFont()
        font8.setPointSize(10)
        font8.setBold(False)
        self.tableWidget.setFont(font8)
        self.tableWidget.setStyleSheet(u"QHeaderView::section {\n"
"    font-size: 10pt;\n"
"}")
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.tableWidget.setAlternatingRowColors(False)

        self.verticalLayout.addWidget(self.tableWidget)


        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 2)

        self.tabWidget.addTab(self.tab, "")
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.verticalLayout_3 = QVBoxLayout(self.tab_1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.groupBox_32 = QGroupBox(self.tab_1)
        self.groupBox_32.setObjectName(u"groupBox_32")
        self.groupBox_32.setEnabled(True)
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.groupBox_32.sizePolicy().hasHeightForWidth())
        self.groupBox_32.setSizePolicy(sizePolicy3)
        self.groupBox_32.setMinimumSize(QSize(647, 151))
        font9 = QFont()
        font9.setFamilies([u"Segoe UI"])
        font9.setPointSize(17)
        font9.setBold(True)
        font9.setUnderline(False)
        self.groupBox_32.setFont(font9)
        self.gridLayout_3 = QGridLayout(self.groupBox_32)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.listWidget = QListWidget(self.groupBox_32)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setMinimumSize(QSize(581, 91))
        font10 = QFont()
        font10.setFamilies([u"Segoe UI"])
        font10.setPointSize(9)
        font10.setBold(False)
        font10.setUnderline(False)
        self.listWidget.setFont(font10)

        self.gridLayout_3.addWidget(self.listWidget, 0, 0, 1, 1)


        self.verticalLayout_3.addWidget(self.groupBox_32)

        self.tabWidget_4 = QTabWidget(self.tab_1)
        self.tabWidget_4.setObjectName(u"tabWidget_4")
        sizePolicy.setHeightForWidth(self.tabWidget_4.sizePolicy().hasHeightForWidth())
        self.tabWidget_4.setSizePolicy(sizePolicy)
        self.tabWidget_4.setMinimumSize(QSize(647, 491))
        self.tabWidget_4.setMaximumSize(QSize(16777215, 16777215))
        font11 = QFont()
        font11.setPointSize(18)
        font11.setBold(True)
        self.tabWidget_4.setFont(font11)
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.groupBox_27 = QGroupBox(self.tab_12)
        self.groupBox_27.setObjectName(u"groupBox_27")
        self.groupBox_27.setEnabled(True)
        self.groupBox_27.setGeometry(QRect(20, 60, 611, 361))
        self.groupBox_27.setMinimumSize(QSize(571, 361))
        self.groupBox_27.setFont(font9)
        self.label_131 = QLabel(self.groupBox_27)
        self.label_131.setObjectName(u"label_131")
        self.label_131.setGeometry(QRect(30, 50, 61, 26))
        font12 = QFont()
        font12.setFamilies([u"Segoe UI"])
        font12.setPointSize(13)
        font12.setBold(False)
        font12.setUnderline(False)
        self.label_131.setFont(font12)
        self.comboBox_27 = QComboBox(self.groupBox_27)
        self.comboBox_27.setObjectName(u"comboBox_27")
        self.comboBox_27.setGeometry(QRect(100, 50, 231, 26))
        self.comboBox_27.setMinimumSize(QSize(231, 26))
        self.comboBox_27.setMaximumSize(QSize(16777215, 26))
        self.comboBox_27.setFont(font10)
        self.pushButton_39 = QPushButton(self.groupBox_27)
        self.pushButton_39.setObjectName(u"pushButton_39")
        self.pushButton_39.setGeometry(QRect(440, 0, 61, 26))
        self.pushButton_39.setMinimumSize(QSize(61, 26))
        self.pushButton_39.setMaximumSize(QSize(61, 26))
        font13 = QFont()
        font13.setFamilies([u"Segoe UI"])
        font13.setPointSize(11)
        font13.setBold(False)
        font13.setUnderline(False)
        self.pushButton_39.setFont(font13)
        self.pushButton_57 = QPushButton(self.groupBox_27)
        self.pushButton_57.setObjectName(u"pushButton_57")
        self.pushButton_57.setGeometry(QRect(510, 0, 91, 26))
        self.pushButton_57.setMinimumSize(QSize(91, 26))
        self.pushButton_57.setMaximumSize(QSize(91, 26))
        self.pushButton_57.setFont(font13)
        self.groupBox_9 = QGroupBox(self.groupBox_27)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(20, 180, 571, 81))
        self.groupBox_9.setMinimumSize(QSize(511, 81))
        font14 = QFont()
        font14.setFamilies([u"Segoe UI"])
        font14.setPointSize(13)
        font14.setBold(False)
        font14.setItalic(False)
        font14.setUnderline(False)
        self.groupBox_9.setFont(font14)
        self.dateTimeEdit_19 = QDateTimeEdit(self.groupBox_9)
        self.dateTimeEdit_19.setObjectName(u"dateTimeEdit_19")
        self.dateTimeEdit_19.setGeometry(QRect(70, 40, 201, 26))
        self.dateTimeEdit_19.setMinimumSize(QSize(181, 26))
        self.dateTimeEdit_19.setMaximumSize(QSize(16777215, 26))
        font15 = QFont()
        font15.setFamilies([u"Segoe UI"])
        font15.setPointSize(9)
        font15.setBold(False)
        font15.setItalic(False)
        font15.setUnderline(False)
        self.dateTimeEdit_19.setFont(font15)
        self.dateTimeEdit_19.setCalendarPopup(True)
        self.label_132 = QLabel(self.groupBox_9)
        self.label_132.setObjectName(u"label_132")
        self.label_132.setGeometry(QRect(30, 40, 41, 26))
        self.label_132.setMinimumSize(QSize(41, 26))
        font16 = QFont()
        font16.setFamilies([u"Segoe UI"])
        font16.setPointSize(11)
        font16.setBold(False)
        font16.setItalic(False)
        font16.setUnderline(False)
        self.label_132.setFont(font16)
        self.label_132.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_133 = QLabel(self.groupBox_9)
        self.label_133.setObjectName(u"label_133")
        self.label_133.setGeometry(QRect(300, 40, 41, 26))
        self.label_133.setMinimumSize(QSize(41, 26))
        self.label_133.setFont(font16)
        self.label_133.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.dateTimeEdit_20 = QDateTimeEdit(self.groupBox_9)
        self.dateTimeEdit_20.setObjectName(u"dateTimeEdit_20")
        self.dateTimeEdit_20.setGeometry(QRect(340, 40, 201, 26))
        self.dateTimeEdit_20.setMinimumSize(QSize(181, 26))
        self.dateTimeEdit_20.setMaximumSize(QSize(16777215, 26))
        self.dateTimeEdit_20.setFont(font15)
        self.dateTimeEdit_20.setCalendarPopup(True)
        self.groupBox_10 = QGroupBox(self.groupBox_27)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(20, 90, 571, 81))
        self.groupBox_10.setMinimumSize(QSize(511, 81))
        self.groupBox_10.setFont(font14)
        self.doubleSpinBox_11 = QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_11.setObjectName(u"doubleSpinBox_11")
        self.doubleSpinBox_11.setGeometry(QRect(340, 40, 201, 26))
        self.doubleSpinBox_11.setMinimumSize(QSize(181, 26))
        self.doubleSpinBox_11.setMaximumSize(QSize(16777215, 26))
        self.doubleSpinBox_11.setFont(font15)
        self.doubleSpinBox_11.setMaximum(999999999.990000009536743)
        self.doubleSpinBox_11.setSingleStep(0.010000000000000)
        self.label_136 = QLabel(self.groupBox_10)
        self.label_136.setObjectName(u"label_136")
        self.label_136.setGeometry(QRect(300, 40, 41, 26))
        self.label_136.setMinimumSize(QSize(41, 26))
        self.label_136.setFont(font16)
        self.label_136.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.doubleSpinBox_12 = QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_12.setObjectName(u"doubleSpinBox_12")
        self.doubleSpinBox_12.setGeometry(QRect(70, 40, 201, 26))
        self.doubleSpinBox_12.setMinimumSize(QSize(181, 26))
        self.doubleSpinBox_12.setMaximumSize(QSize(16777215, 26))
        self.doubleSpinBox_12.setFont(font15)
        self.doubleSpinBox_12.setMaximum(999999999.990000009536743)
        self.doubleSpinBox_12.setSingleStep(0.010000000000000)
        self.label_135 = QLabel(self.groupBox_10)
        self.label_135.setObjectName(u"label_135")
        self.label_135.setGeometry(QRect(30, 40, 41, 26))
        self.label_135.setMinimumSize(QSize(41, 26))
        self.label_135.setFont(font16)
        self.label_135.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_138 = QLabel(self.groupBox_27)
        self.label_138.setObjectName(u"label_138")
        self.label_138.setGeometry(QRect(350, 50, 71, 26))
        self.label_138.setFont(font14)
        self.comboBox_62 = QComboBox(self.groupBox_27)
        self.comboBox_62.setObjectName(u"comboBox_62")
        self.comboBox_62.setGeometry(QRect(430, 50, 151, 26))
        self.comboBox_62.setMinimumSize(QSize(111, 26))
        self.comboBox_62.setMaximumSize(QSize(16777215, 26))
        self.comboBox_62.setFont(font10)
        self.comboBox_62.setEditable(True)
        self.comboBox_62.setMaxVisibleItems(20)
        self.plainTextEdit = QPlainTextEdit(self.groupBox_27)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(20, 280, 571, 61))
        self.plainTextEdit.setFont(font10)
        self.plainTextEdit.setReadOnly(True)
        self.pushButton_79 = QPushButton(self.tab_12)
        self.pushButton_79.setObjectName(u"pushButton_79")
        self.pushButton_79.setGeometry(QRect(350, 20, 81, 26))
        self.pushButton_79.setMinimumSize(QSize(81, 26))
        self.pushButton_79.setMaximumSize(QSize(81, 26))
        self.pushButton_79.setFont(font13)
        self.pushButton_81 = QPushButton(self.tab_12)
        self.pushButton_81.setObjectName(u"pushButton_81")
        self.pushButton_81.setGeometry(QRect(260, 20, 81, 26))
        self.pushButton_81.setMinimumSize(QSize(81, 26))
        self.pushButton_81.setMaximumSize(QSize(81, 26))
        self.pushButton_81.setFont(font13)
        self.pushButton_102 = QPushButton(self.tab_12)
        self.pushButton_102.setObjectName(u"pushButton_102")
        self.pushButton_102.setEnabled(True)
        self.pushButton_102.setGeometry(QRect(470, 20, 26, 26))
        self.pushButton_102.setMinimumSize(QSize(26, 26))
        self.pushButton_102.setMaximumSize(QSize(26, 26))
        font17 = QFont()
        font17.setFamilies([u"Segoe UI"])
        font17.setPointSize(11)
        font17.setBold(True)
        font17.setUnderline(False)
        self.pushButton_102.setFont(font17)
        self.label_5 = QLabel(self.tab_12)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(130, 20, 111, 26))
        self.label_5.setMinimumSize(QSize(111, 26))
        font18 = QFont()
        font18.setPointSize(13)
        font18.setBold(False)
        self.label_5.setFont(font18)
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QWidget()
        self.tab_13.setObjectName(u"tab_13")
        self.pushButton_82 = QPushButton(self.tab_13)
        self.pushButton_82.setObjectName(u"pushButton_82")
        self.pushButton_82.setGeometry(QRect(235, 20, 81, 26))
        self.pushButton_82.setFont(font13)
        self.groupBox_28 = QGroupBox(self.tab_13)
        self.groupBox_28.setObjectName(u"groupBox_28")
        self.groupBox_28.setEnabled(True)
        self.groupBox_28.setGeometry(QRect(20, 60, 611, 361))
        self.groupBox_28.setMinimumSize(QSize(571, 361))
        self.groupBox_28.setFont(font9)
        self.label_134 = QLabel(self.groupBox_28)
        self.label_134.setObjectName(u"label_134")
        self.label_134.setGeometry(QRect(30, 50, 91, 26))
        self.label_134.setFont(font12)
        self.comboBox_28 = QComboBox(self.groupBox_28)
        self.comboBox_28.setObjectName(u"comboBox_28")
        self.comboBox_28.setGeometry(QRect(120, 50, 231, 26))
        self.comboBox_28.setFont(font10)
        self.groupBox_11 = QGroupBox(self.groupBox_28)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(30, 250, 521, 81))
        self.groupBox_11.setFont(font14)
        self.dateTimeEdit_21 = QDateTimeEdit(self.groupBox_11)
        self.dateTimeEdit_21.setObjectName(u"dateTimeEdit_21")
        self.dateTimeEdit_21.setGeometry(QRect(70, 40, 181, 26))
        self.dateTimeEdit_21.setFont(font15)
        self.dateTimeEdit_21.setCalendarPopup(True)
        self.label_139 = QLabel(self.groupBox_11)
        self.label_139.setObjectName(u"label_139")
        self.label_139.setGeometry(QRect(30, 40, 41, 26))
        self.label_139.setFont(font16)
        self.label_139.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_140 = QLabel(self.groupBox_11)
        self.label_140.setObjectName(u"label_140")
        self.label_140.setGeometry(QRect(270, 40, 41, 26))
        self.label_140.setFont(font16)
        self.label_140.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.dateTimeEdit_22 = QDateTimeEdit(self.groupBox_11)
        self.dateTimeEdit_22.setObjectName(u"dateTimeEdit_22")
        self.dateTimeEdit_22.setGeometry(QRect(310, 40, 181, 26))
        self.dateTimeEdit_22.setFont(font15)
        self.dateTimeEdit_22.setCalendarPopup(True)
        self.pushButton_84 = QPushButton(self.groupBox_11)
        self.pushButton_84.setObjectName(u"pushButton_84")
        self.pushButton_84.setGeometry(QRect(440, 0, 71, 26))
        self.pushButton_84.setFont(font16)
        self.label_143 = QLabel(self.groupBox_28)
        self.label_143.setObjectName(u"label_143")
        self.label_143.setGeometry(QRect(30, 90, 91, 26))
        self.label_143.setFont(font14)
        self.comboBox_63 = QComboBox(self.groupBox_28)
        self.comboBox_63.setObjectName(u"comboBox_63")
        self.comboBox_63.setGeometry(QRect(120, 90, 111, 26))
        self.comboBox_63.setFont(font10)
        self.comboBox_63.setEditable(True)
        self.comboBox_63.setMaxVisibleItems(20)
        self.pushButton_83 = QPushButton(self.groupBox_28)
        self.pushButton_83.setObjectName(u"pushButton_83")
        self.pushButton_83.setGeometry(QRect(330, 90, 71, 26))
        self.pushButton_83.setFont(font13)
        self.pushButton_85 = QPushButton(self.groupBox_28)
        self.pushButton_85.setObjectName(u"pushButton_85")
        self.pushButton_85.setGeometry(QRect(250, 90, 71, 26))
        self.pushButton_85.setFont(font13)
        self.label_3 = QLabel(self.groupBox_28)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(60, 130, 451, 101))
        self.label_3.setFont(font10)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.label_3.setWordWrap(True)
        self.pushButton_104 = QPushButton(self.tab_13)
        self.pushButton_104.setObjectName(u"pushButton_104")
        self.pushButton_104.setEnabled(True)
        self.pushButton_104.setGeometry(QRect(350, 20, 26, 26))
        self.pushButton_104.setFont(font17)
        self.tabWidget_4.addTab(self.tab_13, "")

        self.verticalLayout_3.addWidget(self.tabWidget_4)

        self.tabWidget.addTab(self.tab_1, "")

        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.horizontalSpacer_4 = QSpacerItem(14, 728, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer_4, 1, 1, 1, 1)

        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setMinimumSize(QSize(671, 761))
        self.tabWidget_2.setFont(font2)
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.gridLayout_5 = QGridLayout(self.tab_7)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.tableView_3 = QTableView(self.tab_7)
        self.tableView_3.setObjectName(u"tableView_3")
        self.tableView_3.setEnabled(True)
        self.tableView_3.setMinimumSize(QSize(621, 631))
        self.tableView_3.setFont(font8)
        self.tableView_3.setFrameShape(QFrame.Shape.Box)
        self.tableView_3.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_5.addWidget(self.tableView_3, 0, 0, 1, 1)

        self.tabWidget_2.addTab(self.tab_7, "")

        self.gridLayout.addWidget(self.tabWidget_2, 1, 2, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"StormSim: CHS HDF5 Converter", None))
        self.label_10_stormsim_logo.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"CHS HDF5 Converter", None))
        self.label_2_chl_logo.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Instructions", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">1)</span> Download HDF5/ZIP files from the <a href=\"https://chs.erdc.dren.mil/Home/Library\"><span style=\" text-decoration: underline; color:#0000ff;\">Coastal Hazards System</span></a> (CHS) database. <span style=\" font-weight:700;\">2)</span> Use <span style=\" font-style:italic;\">Browse</span> to bring files to <span style=\" font-style:italic;\">Qualifying Files</span>. This ignores incompatible files or duplicate filenames. <span style=\" font-weight:700;\">3)</span> Select files to convert to a table format and <span style=\" font-weight:700;\">export</span> as CSV or <span style=\" font-weight:700;\">import</span> for viewing. Imported files can be exported and filtered later in <span style=\" font-style:italic;\">Data Viewer</span>, but not all files can be imported (&quot;CHS-TX&quot;; &quot;SRR&quot;, &quot;NLR&quot;, &quot;Param&quot;; &quot;TH&quot;, &quot;Post96RT&quot;). <span style=\" font-weight:700;\">4) </span><span style=\" font-sty"
                        "le:italic;\">Add</span> for more files or <span style=\" font-style:italic;\">Clear</span> to remove all files. <span style=\" font-weight:700;\">5)</span> When ready, select <span style=\" font-style:italic;\">Run</span>.</p></body></html>", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Convert Files", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search files", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
#if QT_CONFIG(tooltip)
        self.pushButton_2.setToolTip(QCoreApplication.translate("MainWindow", u"Add HDF5 and/or ZIP files.", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.pushButton_1.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Export", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Import", None));
        ___qtablewidgetitem2 = self.tableWidget.verticalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Filename1", None));
        ___qtablewidgetitem3 = self.tableWidget.verticalHeaderItem(1)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Filename2", None));
        ___qtablewidgetitem4 = self.tableWidget.verticalHeaderItem(2)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Filename3", None));

        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Convert", None))
        self.groupBox_32.setTitle(QCoreApplication.translate("MainWindow", u"Datasets", None))
        self.groupBox_27.setTitle(QCoreApplication.translate("MainWindow", u"Filter", None))
        self.label_131.setText(QCoreApplication.translate("MainWindow", u"Variable", None))
        self.comboBox_27.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Choose a variable", None))
        self.pushButton_39.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.pushButton_57.setText(QCoreApplication.translate("MainWindow", u"Clear All", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Date Range for Variable", None))
        self.label_132.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label_133.setText(QCoreApplication.translate("MainWindow", u"End", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Magnitude Range for Variable", None))
        self.label_136.setText(QCoreApplication.translate("MainWindow", u"Max", None))
        self.label_135.setText(QCoreApplication.translate("MainWindow", u"Min", None))
        self.label_138.setText(QCoreApplication.translate("MainWindow", u"Storm ID", None))
        self.comboBox_62.setPlaceholderText(QCoreApplication.translate("MainWindow", u"-- Type for more --", None))
        self.plainTextEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"No active filters.", None))
#if QT_CONFIG(tooltip)
        self.pushButton_79.setToolTip(QCoreApplication.translate("MainWindow", u"Export the entire table.", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_79.setText(QCoreApplication.translate("MainWindow", u"Full", None))
#if QT_CONFIG(tooltip)
        self.pushButton_81.setToolTip(QCoreApplication.translate("MainWindow", u"Exports current state of the table.", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_81.setText(QCoreApplication.translate("MainWindow", u"Current", None))
        self.pushButton_102.setText(QCoreApplication.translate("MainWindow", u"?", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Export Table >", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"Table", None))
        self.pushButton_82.setText(QCoreApplication.translate("MainWindow", u"Plot", None))
        self.groupBox_28.setTitle(QCoreApplication.translate("MainWindow", u"Filter", None))
        self.label_134.setText(QCoreApplication.translate("MainWindow", u"Variable", None))
        self.comboBox_28.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Choose a variable", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"Date Range for Variable", None))
        self.label_139.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label_140.setText(QCoreApplication.translate("MainWindow", u"End", None))
        self.pushButton_84.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.label_143.setText(QCoreApplication.translate("MainWindow", u"Storm ID(s)", None))
        self.comboBox_63.setPlaceholderText(QCoreApplication.translate("MainWindow", u"-- Type for more --", None))
        self.pushButton_83.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.pushButton_85.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"[No selected Storm IDs]", None))
        self.pushButton_104.setText(QCoreApplication.translate("MainWindow", u"?", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), QCoreApplication.translate("MainWindow", u"Graph", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Data Viewer", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Data Viewer", None))
    # retranslateUi

